name: build
on: [ pull_request, push ]

jobs:
    build:
        strategy:
            matrix:
                java: [
                    21
                ]
        runs-on: ubuntu-22.04
        steps:
            -   uses: wow-rp-addons/actions-editorconfig-check@v1
                with:
                    files: $(git ls-files)
